name: Deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master, develop]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master, develop]

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Print environment
        run: |
          echo "Running in environment: test"
